project:
  type: website
  output-dir: docs

website:
  title: "Yuchen Chen(Vitcor)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.pdf
        text: CV
      - href: Hobbies.pdf
        text: Hobbies

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



